# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1in-p10LB2FjbIy1QcI5Tm0MGzxA1OYam
"""

import sys
input = sys.stdin.readline

def main():
    n = int(input())

    def calc(s):
        res = 0
        for i in range(len(s)):
            if s[i] == '1':
                res += i + 1
        return res % (n + 1)

    def solve(s):
        res = calc(s)

        if len(s) == n:
            if res == 0:
                return s

            for i in range(n):
                if s[i] == '1' and (res - (i + 1)) % (n + 1) == 0:
                    return s[:i] + '0' + s[i + 1:]

        if len(s) == n - 1:
            if res == 0:
                return s + '0'
            if res == 1:
                return s + '1'

            ones = 0
            for i in range(n - 2, -1, -1):
                if s[i] == '1':
                    ones += 1
                if (res + ones) % (n + 1) == 0:
                    return s[:i] + '0' + s[i:]
                if (res + ones + i + 1) % (n + 1) == 0:
                    return s[:i] + '1' + s[i:]

        if len(s) == n + 1:
            ones = 0
            for i in range(n, -1, -1):
                if s[i] == '1':
                    if (res - ones - (i + 1)) % (n + 1) == 0:
                        return s[:i] + s[i + 1:]
                    ones += 1
                else:
                    if (res - ones) % (n + 1) == 0:
                        return s[:i] + s[i + 1:]

    out = ''

    for line in sys.stdin:
        s = line.strip()
        if len(s) == 0:
            continue
        out += solve(s) + '\n'

    sys.stdout.write(out)


main()